services:
    todo-mongo:
        image: mongo:${MONGO_TAG}
        restart: always
        container_name: todo-database
        ports:
            - ${MONGO_PORT}:27017
        networks:
            internal_network:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - ./db:/data/db
            - ./config:/data/configdb
    web:
        container_name: todo-web
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3098:3000
        networks:
            - app_network

networks:
    app_network:
        external: true
    internal_network:
